<a href="https://colab.research.google.com/github/jyothijonnalagadda003/python----Lab/blob/main/harika123.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

NAME:ch.harika ratna chandu

REGNO:19A21A0579

SECTION:CSE-B


**EXCERSICE**-1
A.WRITE PROGRAM IN INTERACTIVE,INTERPRETER,PYHON SCRIPT MODE.

B.Write a program to purposefully raise Indentation Error and Correct **it**

**AIM**:
 
a) Running instructions in Interactive interpreter and a Python Script
 
**DESCRIPTION**:
 
Python is a high-level, interpreted, interactive and object-oriented 
scripting language. 
Python is designed to be highly readable.  It uses English keywords frequently where as other languages use 
punctuation, and it has fewer syntactical constructions than other languages. 
 
* Python is Interpreted 
 
* Python is Interactive 
 
* Python is Object-Oriented
 
* Python is a Beginner's Language
 
**Python Programming Running Python Scripts**
 
Running Python in THREE ways: 
 
a) Running Python Interpreter 
 
b) Running Python Scripts in IDLE 
 
c) Running python scripts in Command Prompt 
 
**a) Running Python Interpreter:**
Python comes with an interactive interpreter. When you type python in your shell or command prompt, the python interpreter becomes active with a >>> prompt and waits for your commands
 
b) **Running Python Scripts in IDLE:**
. Go to File menu click on New File (CTRL+N) and write the 
code and save first.py
 
c) **Running python scripts in Command Prompt: ** 
· Before going to run we have to check the PATH in environment 
variables.

In [ ]:

a=78
b=89
a,b=b,a
print(a,b)


89 78


**AIM**:

 To Write a program to purposefully raise Indentation Error and Correct it
  
  **DESCRIPTION**:

  **Indentation** 
* Python does not support braces to indicate blocks of code for class and 
function definitions or flow control. 

* Blocks of code are denoted by line indentation.

* All the continuous lines indented with same number of spaces would form a block. 

* Python strictly follow indentation rules to indicate the blocks. 


In [ ]:
a=input("enter a vlaue:")
b=input("enter b value:")
c=a+b;
print("sum is ",c,sep="\t")
c=int(a)+int(b)
print("sum of {} and {} is : {}".format(a,b,c))
print("sum of %s and %s is:%d"%(a,b,c))
x=10
y=123
z=x+y;
print("sum is",z,sep='\t' )


enter a vlaue:9
enter b value:7
sum is 	97
sum of 9 and 7 is : 16
sum of 9 and 7 is:16
sum is	133


In [ ]:
print("welcome to python")
a=20
b=30
print("the value of a:",a)
print("the value of b :",b)
if(a>b):
       print("a is big");
       print("ifbblock ends")
else:
            print("b is big")
            print("elseblock ends")



welcome to python
the value of a: 20
the value of b : 30
b is big
elseblock ends


**EXERCISE**-2

A.COMPUTE DISTANCE BETWEEN TWO POINTS

 B.TAKE TWO NUMBERS ON COMMAND LINE ARGUMENTS AND PRINT THE SUM.

**AIM**:

TO COMPUTE DISTANCE BETWEEN TWO POINTS


**DESCRIPTION**:

**Taking Input From the User:**
A function is defined as a block of organized, reusable code used to perform a single, related action. Python has many built-in functions; you can also create your own. 

Python has an input function which lets you ask a user for some text input. You call this function to tell the program to stop and wait for the user to key in the data.

 In Python 2, you have a built-in function raw_input(), whereas in Python 3, you have input(). The program will resume once the user presses the ENTER or RETURN key.

 **Input Function**

input(prompt=None,/). 

Read a string from standard input. The trailing newline is stripped. 

The prompt string, if given, is printed to standard output without a trailing newline before reading input. 

If the user hits EOF (*nix: Ctrl-D, Windows: Ctrl Z+Return), raise EOFError.

In [ ]:
x1=10
x2=80
y1=12
y2=20
z=(pow((x2-x1),2)+pow((y2-y1),2))**0.5
print(z)


70.45565981523414


In [ ]:
import math
x1=int(input("enter  x1 value:"))
x2=int(input("enter  x2 value:"))
y1=int(input("enter  y1 value:"))
y2=int(input("enter  y2 value:"))
z=math.sqrt((x2-x1)**2+(y2-y1)**2)
print("the distance between two points is :",z)
print("the distance between two points is :",z,sep='\t')
print("the distance between ({}, {})and ({},{}) is  :{}".format(x1,y1,x2,y2,z))

print("the distance between (%d, %d)and (%d,%d) is  :%f"%(x1,y1,x2,y2,z))



enter  x1 value:7
enter  x2 value:3
enter  y1 value:6
enter  y2 value:4
the distance between two points is : 4.47213595499958
the distance between two points is :	4.47213595499958
the distance between (7, 6)and (3,4) is  :4.47213595499958
the distance between (7, 6)and (3,4) is  :4.472136


**AIM**:

TAKE TWO NUMBERS ON COMMAND LINE ARGUMENTS AND PRINT THE SUM

**DESCRIPTION**:

The arguments that are given after the name of the program in the command line shell of the operating system are known as Command Line Arguments. Python provides various ways of dealing with these types of arguments. The three most common are:

Using sys.argv

Using getopt module

Using argparse module

Using sys.argv

The sys module provides functions and variables used to manipulate different parts of the Python runtime environment. This module provides access to some variables used or maintained by the interpreter and to functions that interact strongly with the interpreter.

One such variable is sys.argv which is a simple list structure. It’s main purpose are:

It is a list of command line arguments.

len(sys.argv) provides the number of command line arguments.

sys.argv[0] is the name of the current Python script.

In [ ]:
                                
import sys
a=sys.argv[1]
b=sys.argv[2]
sum=int(a)+int(b)
print("summ of two number is:",sum)




**output**



C:\Users\harika\Desktop\python files>python commd.py 10 30
summ of two number is: 40

C:\Users\harika\Desktop\python files>



EXCERSCISE-3
A) Write a Program for checking whether the given number is an even number or not.

b) Using a for loop, write a program that prints out the decimal equivalents of 1/2, 1/3, 1/4, . . .1/10

c) Write a program using a for loop that loops over a sequence. What is sequence?

d) Write a program using a while loop that asks the user for a number, and prints a countdownfrom
that number to zero

**AIM**:

a) Write a Program for checking whether the given number is an even number or not.

**DESCRIPTION**:

if..else Statement When there is an alternate operation in control flow, use an else statement alongside with if statement. The general format is

if condition:

    true statement
else:

     false statement

In [ ]:
n=int(input("enter a number:"))
if (n%2)==0:
        print("given number is even")
else:
      print("given number is odd")

      

enter a number:5
given number is odd


**AIM**:

b) Using a for loop, write a program that prints out the decimal equivalents of 1/2, 1/3, 1/4, . . .1/10

**DESCRIPTION**

For Loop: For loops can iterate over a sequence of numbers using the "range" and "xrange" functions. The difference between range and xrange is that the range function returns a new list with numbers of that specified range, whereas xrange returns an iterator, which is more efficient.

The general format is

for x in range(start,stop,step):

statements

In [ ]:
n=int(input("enter a number:"))
for i in range(2,n):
    de=1/i;
    print("1/",i,"=",de)


enter a number:4
1/ 2 = 0.5
1/ 3 = 0.3333333333333333


**AIM**:

c) Write a program using a for loop that loops over a sequence. What is sequence?

**DESCRIPTION**:

For Loop: For loops can iterate over a sequence of numbers using the "range" and "xrange" functions. The difference between range and xrange is that the range function returns a new list with numbers of that specified range, whereas xrange returns an iterator, which is more efficient.

The general format is

for x in range(start,stop,step):

statements

In [ ]:
#program using a for a loop that loops over a sequence
print("loop sequence")
num=[45,25,2,28,3,25]
for i in num:
    print(i)

#string sequence
print("string sequence")
days=["sun","mon","tue","wed","thur","fri","st"]
for d in days:
    print(d)
    
#bothh sequence
print("sequence")
arr=[123,"abc",5.6,'h',-33,"xy",True]
for x in arr:
      print(x)



loop sequence
45
25
2
28
3
25
string sequence
sun
mon
tue
wed
thur
fri
st
sequence
123
abc
5.6
h
-33
xy
True


**AIM**:

D) Write a program using a while loop that asks the user for a number, and prints a countdownfrom that number to zero.

**DESCRIPTION**:

While Loop is used to execute a block of statements repeatedly until a given condition is satisfied. And when the condition becomes false, the line immediately after the loop in the program is executed. While loop falls under the category of indefinite iteration

The syntax for a while loop is:

while [ condition]

In [ ]:
#countdown seq
n=int(input("enter the numbr:"))
while n>0:
      print(n)
      n=n-1


enter the numbr:7
7
6
5
4
3
2
1


**EXCERCISE**-4
a) Find the sum of all the primes below two million. Each new term in the Fibonacci sequence is
generated by adding the previous two terms. Bystarting with 1 and 2, the first 10 terms will be:
1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

b) By considering the terms in the Fibonacci sequence whose values do not exceed four million,find
the sum of the even-valued terms.



**AIM**:

a) Find the sum of all the primes below two million. Each new term in the Fibonacci sequence is generated by adding the previous two terms. Bystarting with 1 and 2, the first 10 terms will be: 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

**DESCRIPTION**:

A Fibonacci sequence is the integer sequence of 0, 1, 1, 2, 3, 5, 8....

The first two terms are 0 and 1. All other terms are obtained by adding the preceding two terms. This means to say the nth term is the sum of (n-1)th and (n-2)th term

Here, we store the number of terms in nterms. We initialize the first term to 0 and the second term to 1.

If the number of terms is more than 2, we use a while loop to find the next term in the sequence by adding the preceding two terms. We then interchange the variables (update it) and continue on with the process.



In [ ]:
n=int(input("enter   a anum:"))
a=0
b=1
c=a+b
st=""
sum=0
con=0
while con<=n:
    st+=""+str(c)
    sum+=c        
    a=b
    b=c 
    c=a+b
    con+=1
print(st)
print("sum of fibonacii series:",sum)



enter   a anum:4
12358
sum of fibonacii series: 19


**AIM**:

b) By considering the terms in the Fibonacci sequence whose values do not exceed four million,find the sum of the even-valued terms.

**DESCRIPTION**:

A Fibonacci sequence is the integer sequence of 0, 1, 1, 2, 3, 5, 8....

The first two terms are 0 and 1. All other terms are obtained by adding the preceding two terms. This means to say the nth term is the sum of (n-1)th and (n-2)th term

Here, we store the number of terms in nterms. We initialize the first term to 0 and the second term to 1.

If the number of terms is more than 2, we use a while loop to find the next term in the sequence by adding the preceding two terms. We then interchange the variables (update it) and continue on with the process.

In [ ]:
n=int(input("enter a number:"))
c=0


st=""
sum=0

for i in range(2,n):
 state=True
for j in range(2,i):
 if(i%j==0):
        state=False
        break;
 if state==True:
            st+=""+str(i)
            c+=1
            sum+=i

print("prime numbers")
print(st)

print("total count of the prime numbers:",c)
print("sum of all prime nums:",sum)



enter a number:3
prime numbers

total count of the prime numbers: 0
sum of all prime nums: 0


**EXCERCISE**-5
- DS

a) Write a program to count the numbers of characters in the string and store them in adictionary data
structure

b) Write a program to use split and join methods in the string and trace a birthday with adictionary
data structure.

**AIM**:

a) Write a program to count the numbers of characters in the string and store them in adictionary data structure

**DESCRIPTION**:

Given a string, the task is to find the frequencies of all the characters in that string and return a dictionary with key as the character and its value as its frequency in the given string.

Method #1 : Naive method

Simply iterate through the string and form a key in dictionary of newly occurred element or if element is already occurred, increase its value by 1.

Method #2 : Using collections.Counter()

The most suggested method that could be used to find all occurrences is this method, this actually gets all element frequency and could also be used to print single element frequency if required.



In [ ]:
name=input("enter anmae:")
dic={}
for ch in name:
    keys=dic.keys()

    if(ch in keys):
        dic[ch]=dic[ch]+1
    else:
        dic[ch]=1

print("dictinarry is:",dic)       


enter anmae:ha
dictinarry is: {'h': 1, 'a': 1}


**AIM**:

b) Write a program to use split and join methods in the string and trace a birthday with adictionary data structure

**DESCRIPTION**:

Python program to Split a string based on a delimiter and join the string using another delimiter.

Split a string can be quite useful sometimes, especially when you need only certain parts of strings. A simple yet effective example is splitting the First-name and Last-name of a person. Another application is CSV(Comma Separated Files). We use split to get data from CSV and join to write data to CSV.

In Python, we can use the function split() to split a string and

join() to join a string.

In [ ]:
dob={"harika":"23-06-2001","slsd":"14-04-2002"}
name=input("enter which person dob u want:")
l=name.split()
birth=""
for i in l:
    if i in dob.keys():
        pers=i

print("".join([pers,"birthdayis:",dob[pers]]))



enter which person dob u want:harika
harikabirthdayis:23-06-2001


**EXERCISE**-6
DS - Continued

a) Write a program combinelists that combines these lists into a dictionary.

b) Write a program to count frequency of characters in a given file. Can you use characterfrequency to

tell whether the given file is a Python program file, C program file or a text file?

**AIM**:

a) Write a program combinelists that combines these lists into a dictionary.

**DESCRIPTION**:

For this, simply declare a dictionary, and then run nested loop for both the lists and assign key and value pairs to from list values to dictionary.

Most pythonic and generic method to perform this very task is by using zip(). This function pairs the list element with other list element at corresponding index in form of key-value pairs.

In [ ]:
sub=["daa","os","dbms","p&s","ppl","se"]
marks=[85,96,75,65,83,56]
print(sub)
print(marks)
dic=dict(zip(sub,marks))
print(dic)

['daa', 'os', 'dbms', 'p&s', 'ppl', 'se']
[85, 96, 75, 65, 83, 56]
{'daa': 85, 'os': 96, 'dbms': 75, 'p&s': 65, 'ppl': 83, 'se': 56}


**AIM**:

b) Write a program to count frequency of characters in a given file. Can you use characterfrequency to tell whether the given file is a Python program file, C program file or a text file?

**DESCRIPTION**:

approaches to count the number of times a letter appears in a text file in Python.

Method 1: Using the in-built count() method.

Approach:

Read the file.
Store the content of the file in a variable.
Use the count() method with the argument as a letter whose frequency is required.
Display the count of the letter.

In [ ]:

filetypes=['.py','.c','.txt']
fn=input("enter a fikle name:")
f=open(fn,"r")
count=dict()
for  ft in filetypes:
     if(ft in  fn):
           if(ft==".py"):
             print("python file")
           elif(ft==".c"):
             print("cfile")
           elif(ft==".txt"):
             print("text file")


for line in f:
     for ch in line:
          if ch in count:
               count[ch]=count[ch]+1

          else:
              count[ch]=1


print(count)
f.close()

**EXCERCISE**-7
- 7 Files

a) Write a program to print each line of a file in reverse order.

b) Write a program to compute the number of characters, words and lines in a file.


**AIM**

a) Write a program to print each line of a file in reverse order.

**DESCRIPTION**:

The file handling plays an important role when the data needs to be stored permanently into the file. A file is a named location on disk to store related information. We can access the stored information (non-volatile) after the program termination. In Python, files are treated in two modes as text or binary. The file may be in the text or binary format, and each line of a file is ended with the special character. Hence, a file operation can be done in the following order.

 Open a file

 Read or write - Performing operation

 Close the file

In [ ]:
obj=open("/abcd.txt","r")
if obj:
  st=obj.read()
  print("File content is:\n",st)
obj.close()
print()
lines=st.split('\n')
for ln in lines:
  i=len(ln)-1
  while(i>=0):
    print(ln[i],end="")
    i=i-1
  print()
    

File content is:
 this is dimple

elpmid si siht


**AIM**:

b) Write a program to compute the number of characters, words and lines in a file

**DESCRIPTION**:

Given a text file fname, the task is to count the total number of characters, words, spaces and lines in the file.

As we know, Python provides multiple in-built features and modules for handling files. Let’s discuss different ways to calculate total number of characters, words, spaces and lines in a file using Python.

Method #1: Naive approach

In this approach, the idea is to solve the task by developing our own logic. Without using any built-in function of Python, the total number of characters, words, spaces and lines of the file will be calculated.

Method #2: Using some built-in functions and OS module functions

In this approach, the idea is to use the os.linesep() method of OS module to separate the lines on the current platform. When the interpreter’s scanner encounter os.linesep it replaces it with \n character. After that strip() and split() functions will be used to carry out the task.



In [ ]:
obj=open("/abcd.txt","r")
if obj:
    st=obj.read()
    print("file content is:")
obj.close()
print()
nc=nw=nl=0
for ch in st:
    if(ch):
        nc=nc+1
    if(ch==''):
        nw=nw+1
    if(ch=='\n'):
        nl=nl+1

print("number of characters in a file:",nc)
print("number of words in file is:",nw)
print("number of lines ins file:",nl)



file content is:

number of characters in a file: 14
number of words in file is: 0
number of lines ins file: 0


**EXCERCISE**-8
- 8 Functions'

a) Write a function ball collide that takes two balls as parameters and computes if they arecolliding.
Your function should return a Boolean representing whether or not the balls arecolliding.
Hint: Represent a ball on a plane as a tuple of (x, y, r), r being the radius
If (distance between two balls centers) <= (sum of their radii) then (they are colliding)

b) Find mean, median, mode for the given set of numbers in a list.

**AIM**:

a) Write a function ball collide that takes two balls as parameters and computes if they arecolliding. Your function should return a Boolean representing whether or not the balls arecolliding.

Hint: Represent a ball on a plane as a tuple of (x, y, r), r being the radius If (distance between two balls centers) <= (sum of their radii) then (they are colliding)

**DESCRIPTION**

Functions A function in python is a block of code that is defined for doing frequent operations in a particular task. The general format is

def Functionname(arguments):

  Statements
Calling a Function:

A function can be called by its name followed by arguments within parenthesis.

function()

In [ ]:
import math
def ballcollide(b1tup,b2tup):
    x1=b1tup[0]
    y1=b1tup[1]
    x2=b2tup[0]
    y2=b2tup[1]
    r1=b1tup[2]
    r2=b2tup[2]


    d=math.sqrt((x2-x1)**2+(y2-y1)**2)
    if(d<=r1+r2):
      return True
    else:
        return False


ball1=(1,2,3)
ball2=(3,2,1)
c=ballcollide(ball1,ball2)
if(c):
    print("balls are collided")
else:
    print("ball are not collided")



balls are collided


**AIM**:

b) Find mean, median, mode for the given set of numbers in a list

**DESCRIPTION**

**Mean** : The mean is the average of all numbers and is sometimes called the arithmetic mean. This code calculates Mean or Average of a list containing numbers:

**Median** : The median is the middle number in a group of numbers. This code calculates Median of a list containing numbers:

**Mode** : The mode is the number that occurs most often within a set of numbers. This code calculates Mode of a list containing numbers:

We will import Counter from collections library which is a built-in module in Python 2 and 3. This module will help us count duplicate elements in a list. We define a list of numbers and calculate the length of the list. We then call Counter (a dict subclass) which helps to count hashable objects, and we then convert it to dict object. We then initialize a list with a For Loop to compare all the dict values (Number of elements) to the max of all dict values (count of most occurring element) and it returns all the elements equal to max count. If the elements returned are equal to the number of total elements in a list then we print out ‘No mode’, else we print out the modes returned.

In [ ]:
def mean(numlist):
    return sum(numlist)/len(numlist)
def median(numlist):
    numlist.sort()
    print(numlist)
    n=len(numlist)
    print("total",n)
    mid=n//2
    print("mid:",mid)
    if(n%2==0):
        return numlist[mid]
    else:
        return (numlist[mid-1]+numlist[mid])/2
def mode(numlist):
    numlist.sort()
    temp=[]
    i=0
    while i<len(numlist):
        temp.append(numlist.count(numlist[i]))
        i+=1
    dic=dict(zip(numlist,temp))
    modes={k for k, v in dic.items() if(v==max(temp))}
    return modes
list=[1,1,2,2,3,4,5,3,3]
print("mean of guive list:",mean(list))
print("median of guive list:",median(list))

print("mode of guive list:",mode(list))




mean of guive list: 2.6666666666666665
[1, 1, 2, 2, 3, 3, 3, 4, 5]
total 9
mid: 4
median of guive list: 2.5
mode of guive list: {3}


**Exercise** - 9 Functions - Continued

a) Write a function nearly equal to test whether two strings are nearly equal. Two strings a and bare
nearly equal when a can be generated by a single mutation on b.

b) Write a function dup to find all duplicates in the list.

c) Write a function unique to find all the unique elements of a list.

**AIM**:

a) Write a function nearly equal to test whether two strings are nearly

**DESCRIPTION**:

**strlen**() function is used to check wether the two string are nearly equal or not by basis of the Length of those Strings

len(**bold text**) function is an inbuilt function in Python programming language that returns the length of the string.

**len**() is a built-in function in python.You can use the len() to get the length of the given string, array, list, tuple, dictionary, etc.

**Value**: the given value you want the length of.

Return value a return an integer value i.e. the length of the given string, or array, or list, or collections.

Syntax:

len(string)

In [ ]:
def nearlyeq(str1,str2):
    count=0
    i=j=0
    ss=0
    while(i<len(str1)and j<len(str2)):
        if(str1[i]!=str2[j]):
            count+=1
        if(len(str1)>len(str2)):
            i+=1

        elif(len(str1)==len(str2)):
            pass
        else:
            i-=1     
        if(count>1):
             ss-=1
             
        i+=1
        j+=1
        if(count<2):
             ss+=1

    return ss
s1=input("enter a string 1:")
s2=input("enter the string2:")
t=nearlyeq(s1,s2)
if(t>1):
    print("neraly equal0")
else:
    print("not nearly equal")


enter a string 1:harika
enter the string2:revathi
not nearly equal


**AIM**:

b) Write a function dup to find all duplicates in the list.

**DESCRIPTION**:

To check if a list contains any duplicate element follow the following steps,

Add the contents of list in a set.

 As set contains only unique elements, so no duplicates will be added   the the set.
Compare the size of set and list.

     If size of list & set is equal then it means no duplicates in list.

If size of list & set are different then it means yes, there are duplicates in list.

In [ ]:
def dup(list):
  list1=[]
  for i in list:
    count=list.count(i)
    if(count>1 and (i not in list1)):
        list1.append(i)
        
  print("the dups int he list are:",list1)        
list2=[1,2,1,2]

dup(list2)




the dups int he list are: [1, 2]


**AIM**:

c) Write a function unique to find all the unique elements of a list.

**DESCRIPTION**:

To find the unique in the list .There is a Specific Method i.e.,

Method : Traversal of list

Using traversal, we can traverse for every element in the list and check if the element is in the unique_list already if it is not over there, then we can append it in the unique_list.

This is done using one for loop and other if statement which check if the value is in the unique list or not which is equivalent to another for loop.



In [ ]:
def unique(list1):
  list2={}

  for i in list1:
    c=list1.count(i)
    if c==1:
      list2[i]=c
  print("the unique elements in the list are:",list2)

list=[1,2,3,45,45,6,88,88,9]
unique(list)

the unique elements in the list are: {1: 1, 2: 1, 3: 1, 6: 1, 9: 1}


**Exercise** - 10 - Functions - Problem Solving

a) Write a function cumulative product to compute cumulative product of a list of numbers.

b) Write a function reverse to reverse a list. Without using the reverse function.

c) Write function to compute gcd, lcm of two numbers. Each function shouldn’t exceed one line

**AIM**:

a) Write a function cumulative product to compute cumulative product of a list of numbers.

**DESCRIPTION**:

A cumulative product is a sequence of partial products of a given sequence. For example, the cumulative products of the sequence. , are , , .. Cumulative products can be implemented in the Wolfram Language as Rest[FoldList[Times, 1, list]]

cumprod(A,1) works on successive elements in the columns of A and returns the cumulative products of each column. cumprod(A,2) works on successive elements in the rows of A and returns the cumulative products of each row.

umprod() function is used when we want to compute the cumulative product of array elements over a given axis. Syntax : numpy.cumprod(arr, axis=None, dtype=None, out=None) Parameters : arr : [array_like] Array containing numbers whose cumulative product is desired.

In [ ]:
def cumulative_product(list1,n):
    list2=[]
    i=0
    list2.append(list1[i])
    for i in range(1,n):
        v=list1[i]*list2[i-1]
        list2.append(v)
        
    print(list2)
list3=[]
n=int(input("enter size :"))
print("enter the data:")
for i in range(0,n):
    x=int(input())
    list3.append(x)
cumulative_product(list3,n)


enter size :2
enter the data:
1
2
[1, 2]


**AIM**:

b) Write a function reverse to reverse a list. Without using the reverse function.

**DESCRIPTION**:

In this Python code snippet post, we are going to implement a list reverse function from the scratch without using any builtin functions.

Let us see how…

Iterative solution

We can use a for loop to swap the first and last items, the second and the one before the last item and so on until the list is reversed in place. The number of iterations needed is half the list size. If the list has an odd number of items then the middle item will stay in its place.



In [ ]:
def reverse_list(numlist):
    temp=list1[::-1]
    numlist=temp
    return temp
list1=[1,2,3,4]
print("giiven list is :",list1)
print("after reverse function:",reverse_list(list1))
print("after list is:",list1)



giiven list is : [1, 2, 3, 4]
after reverse function: [4, 3, 2, 1]
after list is: [1, 2, 3, 4]


**AIM**:

c) Write function to compute gcd, lcm of two numbers. Each function shouldn’t exceed one line.

DESCRIPTION:
**bold text**
Python provides you an anonymous function called lambda. It can take any number of arguments, but can only have one expression. It can be used to find LCM and GCD values without exceeding each from from one line.

The general format is

lambda arguments: expression

The expression is executed during the function call and the result is returned.

Lambda as a Function

The power of using a lambda expression is implementing it using a function

In [ ]:
gcd=lambda a,b: a if b==0 else gcd(a,a%b)
lcm=lambda a,b: (a*b)/gcd(a,b)

x=4
y=24
print("gcd=",gcd(x,y))
print("lcm=",lcm(x,y))


gcd= 4
lcm= 24.0


**Exercise** 11 - Multi-D Lists

a) Write a program that defines a matrix and prints

b) Write a program to perform addition of two square matrices

c) Write a program to perform multiplication of two square matrices




**AIM**:

a) Write a program that defines a matrix and prints

**DESCRIPTION**:

Lists are a very widely use data structure in python. They contain a list of elements separated by comma. But sometimes lists can also contain lists within them. These are called nested lists or multidimensional lists. In this article we will see how to create and access elements in a multidimensional list.

Methods on Multidimensional lists

append(): Adds an element at the end of the list.

extend(): Add the elements of a list (or any iterable), to the end of the current list.

reverse(): Reverses the order of the list.

In [ ]:


def mat_read(rows,cols):
    mat=[[int(input("Enter the mat[%d,%d] value "%(i,j)))for j in range(cols)]for i in range (rows)]
    return mat
def print_mat(rows,cols,mat):
    for i in range(rows):
        for j in range (cols):
            print(mat[i][j],end='\t')
        print()
    
matA=[[]]
matB=[[]]
mat_sum=[[]]


rows=int(input("Enter the row size "))
cols=int(input("Enter the column size "))

if(rows==cols):
    print("For matrix A")
    matA=mat_read(rows,cols)
    
    print("For matrix B")
    matB=mat_read(rows,cols)
    
    mat_sum=[[matA[i][j]+matB[i][j] for j in range(cols)]for i in range (rows)]

    print("Matrix A ")
    print_mat(rows,cols,matA)
    
    print("Matrix B ")
    print_mat(rows,cols,matB)
    
    print("Matrix A+B = ")
    print_mat(rows,cols,mat_sum)
else:
    print("Matrix Addition is not possible")

Enter the row size 1
Enter the column size 2
Matrix Addition is not possible


**AIM**:

b) Write a program to perform addition of two square matrices

**DESCRIPTION**:

We can perform matrix addition in following ways in Python.

Using for loop:
Explanation :- In this program we have used nested for loops to iterate through each row and each column. At each point we add the corresponding elements in the two matrices and store it in the result.

Using nested list comprehension :

In Python, we can implement a matrix as nested list (list inside a list). We can treat each element as a row of the matrix.

Explanation :-

The output of this program is the same as above. We have used nested list comprehension to iterate through each element in the matrix. List comprehension allows us to write concise codes and we must try to use them frequently in Python. They are very helpful.

uising zip function
Explanation :

The zip function accepts iterator i of each element(list) of matrix, mapping them, adding them using sum() and storing them in the map form.



In [ ]:
def mat_read(rows,cols):
    mat=[[int(input("Enter the mat[%d,%d] value "%(i,j)))for j in range(cols)]for i in range (rows)]
    return mat
def print_mat(rows,cols,mat):
    for i in range(rows):
        for j in range (cols):
            print(mat[i][j],end='\t')
        print()
    
matA=[[]]
matB=[[]]
mat_mul=[[]]


rows=int(input("Enter the row size "))
cols=int(input("Enter the column size "))

if(rows==cols):
    print("For matrix A")
    matA=mat_read(rows,cols)
    
    print("For matrix B")
    matB=mat_read(rows,cols)
    
    mat_mul=[[0 for j in range(cols)]for i in range (rows)]

    for i in range (rows):
        for j in range(cols):
            for k in range(cols):
                mat_mul[i][j]+=matA[i][k]*matB[k][j]

    print("Matrix A ")
    print_mat(rows,cols,matA)
    
    print("Matrix B ")
    print_mat(rows,cols,matB)
    
    print("Matrix A*B = ")
    print_mat(rows,cols,mat_mul)
else:
    print("Matrix multiplication is not possible")

Enter the row size 1
Enter the column size 2
Matrix multiplication is not possible


**AIM**:

c) Write a program to perform multiplication of two square

**DESCRIPTION**:

In Python, we can implement a matrix as nested list (list inside a list).

We can treat each element as a row of the matrix.

For example X = [[1, 2], [4, 5], [3, 6]] would represent a 3x2 matrix.

The first row can be selected as X[0]. And, the element in first row, first column can be selected as X[0][0].

Multiplication of two matrices X and Y is defined only if the number of columns in X is equal to the number of rows Y.

If X is a n x m matrix and Y is a m x l matrix then, XY is defined and has the dimension n x l (but YX is not defined). Here are a couple of ways to implement matrix multiplication in Python.

In [ ]:
def matRead(r,c):
   return[[int(input("[%d,%d]value: "%(i,j)))for j in range(c)] for i in range(r)]

def matDisp(mat,r,c):
    for i in range(r):
        for j in range(c):
            print(mat[i][j],end='\t')
        print()

matA=[[]]
matB=[[]]
matMul=[[]]
rows=int(input("Enter Row Size of the Matrix: "))
cols=int(input("Enter column size of the Matrix: "))
if rows==cols:
    print("Enter Matrix-A: ")
    matA=matRead(rows,cols)

    print("Enter Matrix-B: ")
    matB=matRead(rows,cols)

    matMul=[[0 for j in range(cols)] for i in range(rows)]

    for i in range(rows):
        for j in range(cols):
            for k in range(cols):
                matMul[i][j]+=matA[i][k]*matB[k][j]
                
    print("Matrix-A is: ")
    matDisp(matA,rows,cols)

    print("Matrix-B is: ")
    matDisp(matB,rows,cols)

    print("Multiplication of Matrices is: ")
    matDisp(matMul,rows,cols)
else:
    print("Matrices Multiplication is not possible")

Enter Row Size of the Matrix: 2
Enter column size of the Matrix: 2
Enter Matrix-A: 
[0,0]value: 1
[0,1]value: 2
[1,0]value: 1
[1,1]value: 2
Enter Matrix-B: 
[0,0]value: 1
[0,1]value: 2
[1,0]value: 1
[1,1]value: 2
Matrix-A is: 
1	2	
1	2	
Matrix-B is: 
1	2	
1	2	
Multiplication of Matrices is: 
3	6	
3	6	


**Exercise** 12: Modules

a) Install packages requests, flask and explore them. using (pip)

b) Write a script that imports requests and fetch content from the page. Eg. (Wiki)
c) Write a simple script that serves a simple HTTPResponse and a simple HTML Page

**AIM**:

a) Install packages requests,flask and explore them using(pip)

**DESCRIPTION**:

Installing the pip Python package manager on Windows If you are on Windows, and your installed Python the current version, you already have pip! If your Python installation is not the most recent, the easiest thing to do is to simply reinstall it. Download the Python Windows installer at https://www.python.org/downloads/.

In Windows, the variable that controls which programs are accessible from the command line is path. To modify your path to include Python and pip, we have to add C:\Python27 and C:\Python27\Tools. Edit the Windows path by opening the Windows menu, right-clicking on Computer and clicking on Properties. Under Advanced system settings, click Environment Variables.... Scroll down until you find Path, double-click it, and add ;C:\Python27;C:\Python27\Tools to the end.

Installing packages:

Suppose you want to install a package called requests (which is used to make HTTP requests). You need to issue the following command.

pip install requests

show installed packages

You can use the following command to get information about a installed package, i.e Package name, version, location, dependencies.

pip show package_name

install flask

On Mac and Linux, because you are installing programs outside the user-owned folders, you might have to prepend sudo to the install commands. To install Flask, simply run this:

$ pip install flask

show installed flask

You can use the following command to get information about a installed flask, i.e Package name, version, location, dependencies

$ pip show flask

PROGRAM:

In [ ]:
The requests and flask packages are download from internet using the following commands.
C:\python3.9\scripts>pip install requests

C:\python3.9\scripts>pip show requests

C:\python3.9\scripts>pip install flask

C:\python3.9\scripts>pip show flask

https://drive.google.com/file/d/1H1xDdPf3STLM8BivVum2IE9DHUaVUov5/view?usp=sharing

https://drive.google.com/file/d/1s7OuAcNw0mleuB1PE6DnN93fDFzHaDCd/view?usp=sharing

https://drive.google.com/file/d/1Y5tZqVGVbtNItIsEVKmmv_VCtHo_Gieq/view?usp=sharing

https://drive.google.com/file/d/111lqK5HU4_SpTlOQ_52nEn5g41X-ESkI/view?usp=sharing

**AIM**:

b) Write a scripts that imports requests and fetch content from the page.Eg. (Wiki)code:

**DESCRIPTION**:

The Hypertext Transfer Protocol (HTTP) is an application protocol for distributed, collaborative, hypermedia information systems. HTTP is the foundation of data communication for the World Wide Web.

Python requests

Requests is a simple and elegant Python HTTP library. It provides methods for accessing Web resources via HTTP.

Python requests reading a web page

The get() method issues a GET request; it fetches documents identified by the given URL.

PROGRAM:

In [ ]:
 import requests
r=requests.get('https://www.google.com')
print("status coed:",r.status_code)
print("header content:",r.headers['content-type'])
print(r.text)

status coed: 200
header content: text/html; charset=ISO-8859-1
<!doctype html><html itemscope="" itemtype="http://schema.org/WebPage" lang="en"><head><meta content="Search the world's information, including webpages, images, videos and more. Google has many special features to help you find exactly what you're looking for." name="description"><meta content="noodp" name="robots"><meta content="text/html; charset=UTF-8" http-equiv="Content-Type"><meta content="/logos/doodles/2021/doodle-champion-island-games-september-05-6753651837109292-l.png" itemprop="image"><meta content="Doodle Champion Island Games!" property="twitter:title"><meta content="Feline up for a challenge? Help Lucky claim victory in the Doodle Champion Island Games! #GoogleDoodle " property="twitter:description"><meta content="Feline up for a challenge? Help Lucky claim victory in the Doodle Champion Island Games! #GoogleDoodle " property="og:description"><meta content="summary_large_image" property="twitter:card"><meta 

**AIM**:

c) Write a simple script that serves a simple HTTPResponse and Simple HTML page.

**DESCRIPTION**:

HTTP Protocol

The most important part of a web server is HTTP protocol.So now we will see what exactly this is –

It stands for Hyper Text Transfer Protocol.

It is an application layer protocol that allows web based applications to communicate and exchange data.

The HTTP is the messenger of web.

The computer that communicate via the HTTP must speak the HTTP protocol.

It is a TCP/IP based protocol.

It is used to deliver contents, for eg. images, audios, videos, documents etc.

Using HTTP is the most convenient way to quickly and reliably move data on the web.

HTML stands for hypertext markup language. It is the standard markup language for web pages that define the structure of the content. These elements are the building blocks of any website

In [ ]:
 from flask import Flask,render_template
app=Flask(__name__)
print(app)
@app.route("/")
def main():
  return render_template('login.html')
  if __name__=="__main__":
    app.run(host="127.0.0.1",port=2500)

<Flask '__main__'>


**Exercise** - 13 OOP

a) Class variables and instance variable and illustration of the self-variable

i) Robot

ii) ATM Machine

**AIM**:

a)class variables and instance variable and illustration of the self -variable

**DESCRIPTION**:

Variables are named storage location. In python variables are not defined by its type instead it will be automatically determined by the value assigned to it. To determine the type of a variable a function called type () is used.

class variableis shared by all object instances of a class. ... They are not defined inside any methods of a class. Because a class variable is shared by instances of a class, the Python class owns the variable. As a result, all instances of the class will be able to access that variable

Instance variables are owned by instances of the class. This means that for each object or instance of a class, the instance variables are different. ... Instance variables, owned by objects of the class, allow for each object or instance to have different values assigned to those variables

self variable is used to bind the instance of the class to the instance method. We have to explicitly declare it as the first method argument to access the instance variables and methods. This variable is used only with the instance methods.

PROGRAM:

i)ATM ii)robot

In [ ]:
class ATM :
	def _init_(self):
		self.balance=1000
		
	def check_balance(self):
	      print("The balance in your account is ::",self.balance)
	def withdraw_balance(self):
		print("Enter balance to withdraw")
		self._init_()
		self.amount=int(input())
		if self.amount>self.balance:
			print("Insuffient amount")
		else:
			self.balance-=self.amount
			self.check_balance()
	def deposite_balance(self):
		print("Enter balance to deposite")
		self._init_()
		self.amount=int(input())
		self.balance=self.balance+self.amount
		self.check_balance()
print("Enter     1 for balance checking\n 2 for balance withdraw\n 3 for balance deposite\n")
a=ATM()
while (True):
	choice=int(input("Enter your choice"))
	if choice==1:
		a.check_balance()
	elif choice==2:
		a.withdraw_balance()
	elif choice==3:
		a.deposite_balance()
	else:
		print("Invalid choice")
		break


Enter     1 for balance checking
 2 for balance withdraw
 3 for balance deposite

Enter your choice2
Enter balance to withdraw
200
The balance in your account is :: 800
Enter your choice4
Invalid choice


In [ ]:
class robot_design ():
	name="chitti"
	speed="1ZB"
	memory="1TB"
	version="1.0"
	def update(self):
		print("Entet your robot name,speed,memory,version")
		self.name=input()
		self.speed=input()
		self.memory=input()
		self.version=input()
	def display(self):
		print("Your robot name,speed,memory,version is ::",self.name,self.speed,self.memory,self.version)

r=robot_design()
r.update()
r.display()



Entet your robot name,speed,memory,version
2
ghh
kk
23
Your robot name,speed,memory,version is :: 2 ghh kk 23


 **Exercise** - 14
 
 **GUI**, **Graphics**
 
1. Write a GUI for an Expression Calculator using tk
 
2. Write a program to implement the following figures using turtle

**AIM**:

a. Write a GUI for an Expression Calculator using tk

**DESCRIPTION**:

Tkinter is a Python package which comes with many functions and methods that can be used to create an application. In order to create a tkinter application, we generally create an instance of tkinter frame, i.e., Tk(). It helps to display the root window and manages all the other components of the tkinter application. We can initialize the tkinter instance by assigning the variable to it.

In [ ]:
from tkinter import *

win = Tk() # to create a basic window
win.geometry("312x324")  #for the size of the window 
win.resizable(0, 0)  # to prevent from resizing the window
win.title("Calculator")

# 'btn_click' Function continuously updates the 
# input field whenever you enters a number

def btn_click(item):
    global expression
    expression = expression + str(item)
    input_text.set(expression)

# 'bt_clear' function : used to clear the input field

def bt_clear(): 
    global expression 
    expression = ""
    input_text.set("")

# 'bt_equal':calculates the expression present in input field

def bt_equal():
    global expression
    result = str(eval(expression)) # 'eval':This function is used to evaluates the string expression directly
    input_text.set(result)
    expression = ""

expression = ""

# 'StringVar()' :used to get the instance of input field

input_text = StringVar()

# creating a frame for the input field

input_frame = Frame(win, width=312, height=50, bd=0, highlightbackground="black", highlightcolor="black", highlightthickness=2)

input_frame.pack(side=TOP)

#create a input field inside the 'Frame'

input_field = Entry(input_frame, font=('arial', 18, 'bold'), textvariable=input_text, width=50, bg="#eee", bd=0, justify=RIGHT)

input_field.grid(row=0, column=0)

input_field.pack(ipady=10)
# 'ipady' is internal padding to increase the height of input field

#creating another 'Frame' for the button below the 'input_frame'

btns_frame = Frame(win, width=312, height=272.5, bg="grey")

btns_frame.pack()

# first row

clear = Button(btns_frame, text = "C", fg = "black", width = 32, height = 3, bd = 0, bg = "#eee", cursor = "hand2", command = lambda: bt_clear()).grid(row = 0, column = 0, columnspan = 3, padx = 1, pady = 1)

divide = Button(btns_frame, text = "/", fg = "black", width = 10, height = 3, bd = 0, bg = "#eee", cursor = "hand2", command = lambda: btn_click("/")).grid(row = 0, column = 3, padx = 1, pady = 1)

# second row

seven = Button(btns_frame, text = "7", fg = "black", width = 10, height = 3, bd = 0, bg = "#fff", cursor = "hand2", command = lambda: btn_click(7)).grid(row = 1, column = 0, padx = 1, pady = 1)

eight = Button(btns_frame, text = "8", fg = "black", width = 10, height = 3, bd = 0, bg = "#fff", cursor = "hand2", command = lambda: btn_click(8)).grid(row = 1, column = 1, padx = 1, pady = 1)

nine = Button(btns_frame, text = "9", fg = "black", width = 10, height = 3, bd = 0, bg = "#fff", cursor = "hand2", command = lambda: btn_click(9)).grid(row = 1, column = 2, padx = 1, pady = 1)

multiply = Button(btns_frame, text = "", fg = "black", width = 10, height = 3, bd = 0, bg = "#eee", cursor = "hand2", command = lambda: btn_click("")).grid(row = 1, column = 3, padx = 1, pady = 1)

# third row

four = Button(btns_frame, text = "4", fg = "black", width = 10, height = 3, bd = 0, bg = "#fff", cursor = "hand2", command = lambda: btn_click(4)).grid(row = 2, column = 0, padx = 1, pady = 1)

five = Button(btns_frame, text = "5", fg = "black", width = 10, height = 3, bd = 0, bg = "#fff", cursor = "hand2", command = lambda: btn_click(5)).grid(row = 2, column = 1, padx = 1, pady = 1)

six = Button(btns_frame, text = "6", fg = "black", width = 10, height = 3, bd = 0, bg = "#fff", cursor = "hand2", command = lambda: btn_click(6)).grid(row = 2, column = 2, padx = 1, pady = 1)

minus = Button(btns_frame, text = "-", fg = "black", width = 10, height = 3, bd = 0, bg = "#eee", cursor = "hand2", command = lambda: btn_click("-")).grid(row = 2, column = 3, padx = 1, pady = 1)

# fourth row

one = Button(btns_frame, text = "1", fg = "black", width = 10, height = 3, bd = 0, bg = "#fff", cursor = "hand2", command = lambda: btn_click(1)).grid(row = 3, column = 0, padx = 1, pady = 1)

two = Button(btns_frame, text = "2", fg = "black", width = 10, height = 3, bd = 0, bg = "#fff", cursor = "hand2", command = lambda: btn_click(2)).grid(row = 3, column = 1, padx = 1, pady = 1)

three = Button(btns_frame, text = "3", fg = "black", width = 10, height = 3, bd = 0, bg = "#fff", cursor = "hand2", command = lambda: btn_click(3)).grid(row = 3, column = 2, padx = 1, pady = 1)

plus = Button(btns_frame, text = "+", fg = "black", width = 10, height = 3, bd = 0, bg = "#eee", cursor = "hand2", command = lambda: btn_click("+")).grid(row = 3, column = 3, padx = 1, pady = 1)

# fifth row

zero = Button(btns_frame, text = "0", fg = "black", width = 21, height = 3, bd = 0, bg = "#fff", cursor = "hand2", command = lambda: btn_click(0)).grid(row = 4, column = 0, columnspan = 2, padx = 1, pady = 1)

point = Button(btns_frame, text = ".", fg = "black", width = 10, height = 3, bd = 0, bg = "#eee", cursor = "hand2", command = lambda: btn_click(".")).grid(row = 4, column = 2, padx = 1, pady = 1)

equals = Button(btns_frame, text = "=", fg = "black", width = 10, height = 3, bd = 0, bg = "#eee", cursor = "hand2", command = lambda: bt_equal()).grid(row = 4, column = 3, padx = 1, pady = 1)

win.mainloop()

b. Write a program to implement the following figures using turtle

**DESCRIPTION**:

The turtle module is an extended reimplementation of the same-named module from the Python standard distribution up to version Python 2.5.

It tries to keep the merits of the old turtle module and to be (nearly) 100% compatible with it. This means in the first place to enable the learning programmer to use all the commands, classes and methods interactively when using the module from within IDLE run with the -n switch.

The turtle module provides turtle graphics primitives, in both object-oriented and procedure-oriented ways. Because it uses tkinter for the underlying graphics, it needs a version of Python installed with Tk support.

In [ ]:
import turtle
c=["red","green","blue"]
i=0
turtle.pensize(5)

for angle in range(0,360,30):
    if i>2:
        i=0
    turtle.color(c[i])
    turtle.seth(angle)
    turtle.circle(50)
    i+=1

**output**:

https://drive.google.com/file/d/1eO7D9QdEhvpJ361AQ27u-3vayjNk-W1M/view?usp=sharing

In [ ]:
 import turtle
turtle.pensize(1)
 
for i in range(36):
    for j in range(4):
        turtle.forward(70)
        turtle.left(90)
    turtle.left(10)

**output**:

https://drive.google.com/file/d/1oiosPXpdD-ioDpquXQ0RRgthFwmt1MIj/view?usp=sharing

**Exercise** - 15 - Testing

a) Write a test-case to check the function even numbers which return True on passing a list of all even numbers

b) Write a test-case to check the function reverse string which returns the reversed string

**AIM**:

a) Write a test-case to check the function even numbers which return True on passing a list of all even numbers

**DESCRIPTION**:

TestCase is used to create test cases by subclassing it. The last block of the code at the bottom allows us to run all the tests just by running the file. Basic terms used in the code : assertEqual() – This statement is used to check if the result obtained is equal to the expected result

test case:

A test case is a set of conditions which is used to determine whether a system under test works correctly.

In [ ]:
def even(num):
  st= True
  for i in num:
    if i%2==0:
      st=False
      break
  return st
numbers=[]
print("enter th efive nums:")
for i in range(0,5):
  numbers.append(int(input("enter a value:")))
print(even(numbers))


enter th efive nums:
enter a value:12
enter a value:224
enter a value:15
enter a value:65
enter a value:35
False


**AIM**:

b) Write a test-case to check the function reverse string which returns the reversed string

**DESCRIPTION**:

Python string library does’nt support the in-built “reverse()” as done by other python containers like list, hence knowing other methods to reverse string can prove to be useful. This article discusses several ways to achieve it.

The reversed() returns the reversed iterator of the given string and then its elements are joined empty string separated using join(). And reversed order string is formed.



In [ ]:
def revs(str):
  return str[::-1]
st="harika"
print("given string is:",st)
print(revs(st))


given string is: harika
akirah


EXERCISE-16:ADVANCED A) BUILD ANY ONE CLASSICAL DATA STRUCTURE.
 B) WRITE A PROGRAM TO SOLVE KNAPSACK PROBLEM.

**AIM**:

a) Build any one classical data structure.

**DESCRIPTION**:

**What is a Data Structure**
Organizing, managing and storing data is important as it enables easier access and efficient modifications. Data Structures allows you to organize your data in such a way that enables you to store collections of data, relate them and perform operations on them accordingly.

Stack Stacks are linear Data Structures which are based on the principle of Last-In-First-Out (LIFO) where data which is entered last will be the first to get accessed. It is built using the array structure and has operations namely, pushing (adding) elements, popping (deleting) elements and accessing elements only from one point in the stack called as the TOP. This TOP is the pointer to the current position of the stack. Stacks are prominently used in applications such as Recursive Programming, reversing words, undo mechanisms in word editors and so forth.



**AIM**:

b) Write a program to solve knapsack problem

**DESCRIPTION**:

Python Program for 0-1 Knapsack Problem

Problem statement − We are given weights and values of n items, we need to put these items in a bag of capacity W up to the maximum capacity w. We need to carry a maximum number of items and return its value.

Brute-force approach.

dynamic approach.



In [ ]:
 import sys
a=[]
 
while True:
  print ("\nl.PUSH 2.POP 3.DISPLAY 4.EXIT")
  ch=int(input("Enter Your Choice: "))
  if ch==1:
   ele=int(input("Enter element: "))
   a.append(ele)
   print("Inserted")
  elif ch==2:
   if len(a)==0:
     print ("\t STACK IS EMPTY")
   else:
     print ("Deleted element is: ",a[len(a)-1])
     a.remove(a[len(a)-1])
  elif ch==3:
   if len(a)==0:
     print ("\t STACK IS EMPTY")
   else:
    print ("The Elements in Stack is: ")
    for i in reversed(a):
       print(i)
  elif ch==4:
       sys.exit()
  else:
   print ("\tINVALID CHOICE")

**output**

1.PUSH 2.POP 3.DISPLAY 4.EXIT
Enter Your Choice:1
Enter Element: 10
Inserted

1.PUSH 2.POP 3.DISPLAY 4.EXIT
Enter Your Choice:1
Enter Element: 16
Inserted

1.PUSH 2.POP 3.DISPLAY 4.EXIT

Enter Your Choice:1

Enter Element: 4

Inserted

1.PUSH 2.POP 3.DISPLAY 4.EXIT

Enter Your Choice:

	 The Elements in Stack is: 

4
16
10
5

1.PUSH 2.POP 3.DISPLAY 4.EXIT

Enter Your Choice:2

Deleted element is: 4

1.PUSH 2.POP 3.DISPLAY 4.EXIT

Enter Your Choice:2

Deleted element is: 16

1.PUSH 2.POP 3.DISPLAY 4.EXIT

Enter Your Choice:3

	 The Elements in Stack is: 
   10
5

1.PUSH 2.POP 3.DISPLAY 4.EXIT

Enter Your Choice:4

system exit.


In [ ]:
def knapSack(W,wt,val,n):
    K=[[0 for x in range(W+1)] for x in range(n+1)]
    for i in range(n+1):
        for w in range(W+1):
            if i==0 or w==0:
                K[i][w]=0
            elif wt[i-1]<=w:
                K[i][w]=max(val[i-1]+K[i-1][w-wt[i-1]],K[i-1][w])
            else:
                K[i][w]=K[i-1][w]
    return K[n][W]
val=[5,3,4]
wt=[3,2,1]
W=5
n=len(val)
print("Maximum value knapsack of capacity W: ",knapSack(W,wt,val,n))

**output**


Maximum value knapsack of capacity W:  9

EXERCISE 17 & 18-DATA ANALYSIS DATA ANALYSIS OR MANIPULATION USING THE FOLLOWING PACKAGES A) NUMPY B) PANDAS A) SCIPY B) MATPLOTLIB

**AIM**:

Data analysis or manipulation using the following packages
a) Numpy b) Pandas a) Scipy b) matplotlib
**DESCRIPTION**:

Learn how to analyze data using Python. ... It includes following parts: Data Analysis libraries: will learn to use Pandas, Numpy and Scipy libraries to work with a sample dataset. We will introduce you to pandas, an open-source library, and we will use it to load, manipulate, analyze, and visualize cool datasets.

**SciPy** is a free and open-source Python library used for scientific computing and technical computing. It is a collection of mathematical algorithms and convenience functions built on the NumPy extension of Python

**NumPy** is the fundamental package for scientific computing in Python. ... NumPy arrays facilitate advanced mathematical and other types of operations on large numbers of data.

**Matplotlib** is a plotting library for the Python programming language and its numerical mathematics extension NumPy. It provides an object-oriented API for embedding plots into applications using general-purpose GUI toolkits like Tkinter, wxPython, Qt, or GTK

**Pandas** is an open source Python package that is most widely used for data science/data analysis and machine learning tasks. It is built on top of another package named Numpy, which provides support for multi-dimensional arrays.

Scikit-learn is probably the most useful library for machine learning in Python. The sklearn library contains a lot of efficient tools for machine learning and statistical modeling including classification, regression, clustering and dimensionality reduction.

Seaborn is a library in Python predominantly used for making statistical graphics. Seaborn is a data visualization library built on top of matplotlib and closely integrated with pandas data structures in Python

**PROGRAM:**

In [ ]:
#Python version
import sys
print('Python: {}'.format(sys.version))
 
#scipy
import scipy
print('scipy: {}'.format(scipy.__version__))
 
# numpy
import numpy
print( 'numpy: {}'.format(numpy.__version__))
 
# matplotlib
import matplotlib
print('matplotlib: {}'.format(matplotlib.__version__))
 
# pandas
import pandas
print('pandas: {}'.format(pandas.__version__))
 
#scikit-learn
import sklearn
print('sklearn: {}'.format(sklearn.__version__))
import seaborn
print('seaborn: {}'.format(seaborn.__version__))
import urllib
print('urlib: {}'.format(urllib.__name__))
import csv
print('csv: {}'.format(csv.__version__))

# **NumPy**

In [ ]:
import numpy as np
a=np.array([0,1,2])
print(type(a))
print(a.shape)
print(a[0])
print(a[1])
print(a[2])
a[0]=5
print(a)


<class 'numpy.ndarray'>
(3,)
0
1
2
[5 1 2]


In [ ]:
import numpy as np
b=np.array([[0,1,2],[3,4,5]])
print(b.shape)
print(b)
print(b[0,0],b[0,1],b[1,0])


(2, 3)
[[0 1 2]
 [3 4 5]]
0 1 3


In [ ]:
import numpy as np
a=np.zeros((3,3))
print(a)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [ ]:
import numpy as np
b=np.ones((2,2))
print(b)

[[1. 1.]
 [1. 1.]]


In [ ]:
import numpy as np
c=np.full((3,3),7)
print(c)

[[7 7 7]
 [7 7 7]
 [7 7 7]]


In [ ]:
import numpy as np
d=np.random.random((3,3))
print(d)

[[0.40999957 0.77751751 0.27303152]
 [0.57004061 0.19442294 0.89532151]
 [0.69713675 0.27262891 0.19772519]]


In [ ]:
import numpy as np
e=np.eye(3)
print(e)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [ ]:
import numpy as np
f=np.array([2,3,1,0])
print(f)

[2 3 1 0]


In [ ]:
import numpy as np
g=np.arange(2,10)
print(g)

[2 3 4 5 6 7 8 9]


# **Pandas**

# **1.Creating Series**

In [ ]:
import pandas as pd
s=pd.Series([1,2,3,4,5],index=['A','B','C','D','E'])
s

A    1
B    2
C    3
D    4
E    5
dtype: int64